enum EventsType {
  POINTS = 'POINTS',
  SCORE_RESET = 'SCORE_RESET',
  SCORES_RESET = 'SCORES_RESET',
  GAME_RESET = 'GAME_RESET',
  NEW_TURN = 'NEW_TURN',
  PLAYER_REMOVED = 'PLAYER_REMOVED',
  PLAYER_JOINED = 'PLAYER_JOINED',
  CUSTOM = 'CUSTOM',
}

export default EventsType;
